# Site Settings
title: My Awesome GitHub Pages Blog
email: your.email@example.com
description: > # Site description
  A website using Minima with automatic light/dark mode switching.
author: Partha

# Theme Settings
theme: minima

minima:
  skin: dark

# Navigation links that appear in the header
header_pages:
  - index.md
  - blogs.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
