# --- Site Metadata ---
title: My DB
author: Partha
description: >
  feel free to explore my knowledge database.

remote_theme: jekyll/minima

markdown: kramdown

kramdown:
  input: GFM
  parser_block_html: true
  hard_wrap: false

minima:
  skin: auto
  social_links:
    - title: myrepository
      icon: github
      url: "https://github.com/parth721"
    - title: myemail
      icon: at
      url: "mailto:ghoshparth630@gmail.com"

header_pages:
  - blogs.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

