# Site Settings
title: SweetHome
email: your.email@example.com
description: > # Site description
  A website using Minima with automatic light/dark mode switching.
author: Partha

# Theme Settings
remote_theme: jekyll/minima

minima:
  skin: dark 

# Navigation links that appear in the header
header_pages:
  - index.md
  - blogs.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
