# --- Site Metadata ---
title: My DB
author: Partha
description: >
  feel free to explore my knowledge database.

remote_theme: jekyll/minima

markdown: kramdown

kramdown:
  input: GFM
  parser_block_html: true
  hard_wrap: false

minima:
  skin: auto
  social_links:
    - title: github
      icon: github
      url: "https://github.com/parth721"
    - title: email
      icon: inbox
      url: "mailto:ghoshparth630@gmail.com"
    - title: signal-messenger
      icon: signal-messenger
      url: "https://signal.me/#eu/5KdE4BZ7EwSvqMcuQtP5RGpIB-0a26ytbaXJNuEHGm0B5IiB9L9IpZ8ZWXoeJDl0"

header_pages:
  - blogs.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

