# --- Site Metadata ---
title: My DB
author: Partha
email: your.email@example.com
description: >
  feel free to explore my knowledge database.

remote_theme: jekyll/minima

minima:
  skin: auto

header_pages:
  - index.md
  - blogs.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
