# --- Site Metadata ---
title: My DB
author: Partha
description: >
  feel free to explore my knowledge database.

remote_theme: jekyll/minima

markdown: kramdown

minima:
  skin: auto

header_pages:
  - blogs.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
